---
- hosts: centos
  become: true
  tasks:
  - name: update the system
    yum:
      name: "*"
      state: latest

  - name: restart system to reboot to newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: wait for 10 seconds
    pause:
      seconds: 10
